apiVersion: "v1"
name: loki
version: 1.0.0-bb.0
appVersion: v2.4.2
kubeVersion: "^1.10.0-0"
description: "Loki: like Prometheus, but for logs."
home: https://grafana.com/loki
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
sources:
  - https://github.com/grafana/loki
maintainers:
  - name: Loki Maintainers
    email: lokiproject@googlegroups.com
engine: gotpl
dependencies:
  - name: gluon
    version: 0.2.4
    repository: "oci://registry.dso.mil/platform-one/big-bang/apps/library-charts/gluon"
  - name: loki-simple-scalable
    repository: file://deps/loki-simple-scalable
    version: 0.2.0
    condition: loki-simple-scalable.enabled
  - name: loki
    repository: file://deps/loki
    version: 2.10.1
    condition: loki.enabled
