dependencies:
  - name: gluon
    version: 0.2.4
    repository: "oci://registry.dso.mil/platform-one/big-bang/apps/library-charts/gluon"
  - name: loki-simple-scalable
    repository: file://deps/loki-simple-scalable
    version: 0.2.0
    condition: loki-simple-scalable.enabled
  - name: loki
    repository: file://deps/loki
    version: 2.10.1
    condition: loki.enabled
