dependencies:
  - name: gluon
    version: 0.2.4
    repository: "oci://registry.dso.mil/platform-one/big-bang/apps/library-charts/gluon"
  - name: loki-simple-scalable
    version: "*.*.*"
    condition: loki-simple-scalable.enabled
  - name: loki
    version: "*.*.*"
    condition: loki.enabled
  - name: minio
    alias: minio
    version: 8.0.10
    repository: https://helm.min.io/
    condition: minio.enabled
