
domain: bigbang.dev

istio:
  enabled: false
  loki:
    gateways:
    - "istio-system/main"
    hosts:
    - loki.{{ .Values.domain }}

monitoring:
  enabled: false


networkPolicies:
  enabled: false
  controlPlaneCidr: 0.0.0.0/0

monolith:
  enabled: true
  image:
    repository: registry1.dso.mil/ironbank/opensource/grafana/grafana-loki
    tag: 2.3.0
    pullPolicy: IfNotPresent
    pullSecrets:
    - private-registry
  annotations:
    istioVersion: 

scalable:
  enabled: false
  loki:
    image:
      registry: registry1.dso.mil
      repository: ironbank/opensource/grafana/grafana-loki
      tag: 2.3.0
      pullPolicy: IfNotPresent
      pullSecrets:
      - private-registry

global:
  image: 
    registry: registry1.dso.mil
    repository: ironbank/opensource/grafana/grafana-loki
    tag: 2.3.0
    pullPolicy: IfNotPresent
    pullSecrets:
    - private-registry
