apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.readFullname" . }}
  labels:
    {{- include "loki.readLabels" . | nindent 4 }}
    {{- with .Values.read.serviceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-query
      port: 3100
      targetPort: http
      protocol: TCP
    - name: tcp-grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "loki.readSelectorLabels" . | nindent 4 }}
