apiVersion: v2
name: loki-simple-scalable
description: Helm chart for Grafana Loki in simple, scalable mode
type: application
appVersion: 2.4.1
version: 0.1.0
home: https://grafana.github.io/helm-charts
sources:
  - https://github.com/grafana/loki
  - https://grafana.com/oss/loki/
  - https://grafana.com/docs/loki/latest/
icon: https://grafana.com/docs/loki/latest/logo_and_name.png
maintainers:
  - name: trevorwhitney
