{{- if not .Values.gel.useExternalConfig -}}
apiVersion: v1
kind: Secret
metadata:
  name: enterprise-logs-config
  labels:
    {{- include "enterprise-logs.labels" . | nindent 4 }}
data:
  config.yaml: {{ tpl .Values.gel.config . | b64enc }}
  loki.yaml: {{ tpl .Values.gel.config . | b64enc }}
{{- end }}
